version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contactserver
      POSTGRES_USER: contactserver
      POSTGRES_PASSWORD: contactserver
    volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: