import { Entity, Column, PrimaryGeneratedColumn, OneToMany } from 'typeorm';
import { User } from './user.entity';
import { Contact } from './contact.entity';
import { ApiProperty } from '@nestjs/swagger';

@Entity()
export class Organization {
  @ApiProperty({
    description:
      'UUID string. Generated by the API when creating. Immutable for the lifetime of the card.',
    required: false,
  })
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ApiProperty({
    description: 'Name. Must be unique to the Organization',
    required: true,
  })
  @Column({ name: 'name', nullable: false, length: 50 })
  name: string = '';

  @ApiProperty({
    description: 'Users in Organization.',
    required: false,
  })
  @OneToMany(() => User, (user) => user.organization)
  users?: User[];

  @ApiProperty({
    description: 'Contacts in Organization.',
    required: false,
  })
  @OneToMany(() => User, (contact) => contact.organization)
  contacts?: Contact[];
}
